name: Buildpack for FastAPI

on:
  # push: 
  #   branches: ["main"]
  workflow_dispatch:
 

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # setup Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      
      # Setup the App's Python environment
      - name: Install App Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: setup pack
        uses: buildpacks/github-actions/setup-pack@v5.0.0
      - name: Run pack and create container
        run: |
          pack build --builder gcr.io/buildpacks/builder:google-22 jmitchel3/buildpacks-fastapi
      - name: Push to DockerHub
        run: |
          docker push jmitchel3/buildpacks-fastapi  --all-tags